language: android
sudo: false
jdk:
- oraclejdk8
#branches:
#- master
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - android-23
  - android-22
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
script:
- "./gradlew --no-daemon testCnmDebugUnitTest --stacktrace"
before_script:
- "./travis_before_script.sh"
- "ls -la app"
- "ls -la app/src/cnm/res/raw/"
notifications:
  slack:
    secure: V8Wxde5RTNbNiOzulv6idvMpbWtjVc4DPwApjAgfDI01OD6nLkuogr/z3qqyKbA/uwWnzu5g7+vegFtSdjW1z32kiIO0bO2c0m2L/E542D1/zmWT9N0IPghQIZ+9BAj1ZrgG286tiX85lSV8uLy0r9bAefPWlbdrHhirYi3cTsI=
  email: true
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
