package org.eyeseetea.malariacare.data.database.datasources.strategies;

import org.eyeseetea.malariacare.data.IDataSourceCallback;
import org.eyeseetea.malariacare.data.database.datasources.AuthenticationLocalDataSource;
import org.eyeseetea.malariacare.data.database.model.OptionDB;
import org.eyeseetea.malariacare.data.database.model.QuestionDB;
import org.eyeseetea.malariacare.data.database.model.QuestionOptionDB;
import org.eyeseetea.malariacare.data.database.utils.PreferencesCNM;

import java.util.List;


public class AuthenticationLocalDataSourceStrategy extends AAuthenticationLocalDataSourceStrategy {
    public AuthenticationLocalDataSourceStrategy(
            AuthenticationLocalDataSource authenticationLocalDataSource) {
        super(authenticationLocalDataSource);
    }

    @Override
    public void logout(IDataSourceCallback<Void> callback) {
        deleteOrgUnitQuestionOptions();
        super.logout(callback);
        PreferencesCNM.setMetadataDownloaded(false);
    }



    public void deleteOrgUnitQuestionOptions() {
        //Remove options generated by the selected orgunit children
        List<QuestionDB> questionDBs = QuestionDB.getAllQuestionsWithOrgUnitDropdownList();
        for (QuestionDB questionDB : questionDBs) {
            if (questionDB.getAnswerDB() != null) {
                List<OptionDB> optionDBs = questionDB.getAnswerDB().getOptionDBs();
                for (OptionDB optionDB : optionDBs) {
                    optionDB.delete();
                }
            }
        }
    }
}
